name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Check package
        uses: actions/checkout@master
        env:
          R_LIBS_USER: ~/R/library
      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-dev libssl-dev
      - name: Run a multi-line script
        run:
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Setting up R library
        run: |
          echo 'options(repos = "$(CRAN)", Ncpus = 2, crayon.enabled = TRUE)' > ~/.Rprofile
          mkdir -p $(R_LIBS_USER)
      - name: Install package dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check package
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error', check_dir = 'check')"
